CREATE TABLE estugrupos (
    ind bigint NOT NULL,
    codigo bigint NOT NULL,
    estudiante bigint NOT NULL,
    nombres varchar,
    asignacion int,
    institucion_externa varchar NOT NULL,
    genero varchar NOT NULL,
    fecnac date NOT NULL,
    edad int NOT NULL,
    nivel int,
    grado varchar,
    numero int NOT NULL,
    anio int NOT NULL,
    pass varchar NOT NULL,
    activo varchar,
    banda varchar NOT NULL,
    HED varchar NOT NULL,
    idacudiente varchar NOT NULL,
    acudiente varchar NOT NULL,
    telefono1 varchar NOT NULL,
    telefono2 varchar NOT NULL,
    direccion varchar NOT NULL,
    email_estudiante varchar NOT NULL,
    email_acudiente varchar NOT NULL,
    desertor varchar NOT NULL DEFAULT N,
    otraInformacion varchar NOT NULL,
    estado varchar NOT NULL,
    year int NOT NULL,
    lugar varchar NOT NULL,
    sisben varchar NOT NULL,
    estrato varchar NOT NULL,
    lugarNacimiento varchar NOT NULL,
    lugarExpedicion varchar NOT NULL,
    fechaExpedicion varchar NOT NULL,
    tdei varchar NOT NULL,
    victimaConflicto varchar NOT NULL,
    lugarDesplazamiento varchar NOT NULL,
    fechaDesplazamiento varchar NOT NULL,
    etnia varchar NOT NULL,
    tipoSangre varchar NOT NULL,
    eps varchar NOT NULL,
    padre varchar NOT NULL,
    padreid varchar NOT NULL,
    telefonopadre varchar NOT NULL,
    ocupacionpadre varchar NOT NULL,
    madre varchar NOT NULL,
    madreid varchar NOT NULL,
    telefonomadre varchar NOT NULL,
    ocupacionmadre varchar NOT NULL,
    parentesco varchar NOT NULL,
    discapacidad varchar NOT NULL,
    telefono_acudiente varchar NOT NULL,
    eanterior varchar NOT NULL
);

CREATE TABLE excusas (
    ind int NOT NULL,
    estudiante bigint NOT NULL,
    fecha date NOT NULL,
    causa text NOT NULL,
    motivo varchar NOT NULL,
    periodo varchar NOT NULL,
    horas time NOT NULL,
    motivo_permiso varchar NOT NULL,
    hora_salida varchar NOT NULL,
    acudiente varchar NOT NULL,
    otros varchar NOT NULL,
    telefono_acudiente varchar NOT NULL,
    fechahora timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    year int NOT NULL
);